NAME : realProblem96
TYPE : TSP
DIMENSIONS : 96
DATA
1 Poljanski nasip 30
2 Pražakova ulica 3
3 Zaloška cesta 57
4 Dunajska cesta 141
5 Riharjeva ulica 38
6 Vodnikova cesta 235
7 Resljeva cesta 14
8 Šentvid Prušnikova ulica 2
9 Glavarjeva cesta 39
10 Črnuče Dunajska cesta 361
11 Trdinov trg 8 A
12 Ljubljanska cesta 14 A
13 Vegova ulica 1
14 Polje Zadobrovška cesta 14
15 Partizanska cesta 7
16 Gorica Ploščad Osvobodilne fronte 4
17 Kolodvorska ulica 2
18 Ljubljanska cesta 23
19 pri Lj. Podpeška cesta 20
20 Molkov trg 12
21 Poštna ulica 2
22 ob Savi Cesta zmage 28
23 Trg revolucije 27
24 Trg Franca Fakina 4
25 Istrska ulica 49
26 Šarhova ulica 59 A
27 Vrh Sladki Vrh 3 A
28 Malečnik 56
29 v Slovenskih goricah Partizanska cesta 3
30 Čolnikov trg 9
31 Duplek Cesta k Dravi 5
32 Mariborska Cesta 19
33 Ivanjkovci 9 B
34 Poštna ulica 2
35 Gorišnica 79
36 pri Ptuju Videm pri Ptuju 51 A
37 Polskava Mariborska ulica 26
38 Makole 37
39 Kopališka ulica 2
40 Ljubljanska cesta 14
41 Cesta v Rošpoh 18
42 ob Dravi Slovenski trg 4
43 Obrobna ulica 1
44 Glavni trg 31
45 Trg 4. julija 1
46 na Koroškem Trg svobode 19
47 Trg 32 A
48 na Koroškem Center 16
49 Krekov trg 9
50 pri Jelšah Aškerčev trg 26
51 Ulica heroja Staneta 1
52 Malteška cesta 38
53 Savinjska cesta 3
54 Dražgoška ulica 8
55 Škofjeloška cesta 17
56 Jezerska cesta 41
57 Ulica Lojzeta Hrovata 2
58 Glavna cesta 24
59 Gasilska cesta 2 A
60 Loka Kapucinski trg 14
61 Trg svobode 1
62 Na Kresu 1
63 Alpska cesta 37 B
64 Bistrica Trg svobode 2 C
65 Cesta Cirila Tavčarja 8
66 Žirovnica 4
67 Gora Borovška cesta 92
68 Predilniška cesta 10
69 Gorica Kidričeva ulica 19
70 Gorica Industrijska cesta 9
71 Trg maršala Tita 10
72 Goriška cesta 24
73 Vodnikova ulica 1
74 pri Gorici Vrtojbenska cesta 19 C
75 Kolodvorska cesta 9
76 Partizanska cesta 48 A
77 Ulica 1. maja 2 A
78 Cankarjev drevored 1
79 mesto Ulica Slavka Gruma 7
80 mesto Novi trg 7
81 Goliev trg 11
82 Cesta na Fužine 3
83 Ulica stare pravde 34
84 Ulica bratov Gerjovičev 52
85 na Dolenjskem Jesenice 9
86 Trg Matije Gubca 1
87 Trg svobode 9
88 Prvomajska cesta 3
89 Naselje Borisa Kidriča 2
90 Kolodvorska cesta 30 A
91 Sobota Trg Zmage 6
92 Gornji Petrovci 40 E
93 Trg ljudske pravice 7
94 Ulica Prekmurske čete 14
95 Radgona Cesta na Stadion 1
96 Panonska cesta 5
